### ISSUE TITLE
Atmos perfomance

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#197]
It is possible to enchance the atmos perfomance in many various ways (group processing, area processing, etc etc). For a while current implementation is fine, but changes will be needed.

**Comment by kremius** [comment]
Maybe just processing it in separate thing will be fine

**Comment by shelltitan** [comment]
Wouldn't it be a solutions if we make areas and areas would contain the tile based system but in not used places we would use a fastgasexchange() that would do the same as for tile just in area, and we would make an `atomosevent()` function that is used to detect atmos related events in that case the areas where this can have a real in-game effect would be calculated as tile for a time.

**Comment by kremius** [comment]
It is valid approach, but it basically means that if something huge and interesting will happen (singularity outbreak with meteorits and something else) then it will be just ususal per tile atmos, and it is not really good. 
Anyway, seems like new atmos works pretty well (300x300 grid works just fine), so it will not be needed to get rid of the tile atmos - just various tweaks are needed, but the issue is solved overall.

**Comment by shelltitan** [comment]
Well yes at high event number this would just do thing at unused corner tiles.

**Comment by kremius** [comment]
Everything is signed now:
1. Gases amounts may be negative (not really much, but still)
2. Overflow?

**Comment by kremius** [comment]
Pressure visual representation for debugging

**Comment by kremius** [comment]
Somehow make pressure visible for debugging (maybe some special item which will change color on certain pressure?)

**Comment by kremius** [comment]
#320 will help to look into gas movement tick-by-tick

**Comment by kremius** [comment]
Overlays/underlays should have x/y shifts

**Comment by kremius** [comment]
Remote door opener

**Comment by kremius** [comment]
- There is no wind in small corridors (~3 tiles)
- Check if current `Prepare` stage is correct (cover all tiles only once)

**Comment by shelltitan** [comment]
@kremius If this code run on GPU wouldn't it be faster?

**Comment by kremius** [comment]
@shelltitan I have thought about it, but in reality it is impossible
 - it may cause various issues with drawing
 - there is no stable API (?) for such things
 - it is impossible to just run code on GPU. It will be needed to rewrite everything in some special multithreading style, and it is not easy.
 - some machines do not have GPU (e.g. servers)

**Comment by shelltitan** [comment]
@kremius Yeah I thought about servers too, as for API I heard OpenCL is made for this purpose.

**Comment by kremius** [comment]
Seems like done
