### ISSUE TITLE
If item is located on closet then it is impossible to touch item

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#216]
It happens because closet sides (D_LEFT and etc) are not passable.

**Comment by shelltitan** [comment]
Making a new passable level maybe would work , because if a closet will be surrounded by glass windows then you shouldn't be able to touch it so adding it as an exception would be not a good idea.

**Comment by kremius** [comment]
It should not be exception. Just closet sides should be passable, and `D_ALL` (center of the closet) should be not passable.
Closet should have own implementation of  `GetNeighbour` which will return itself, and own `Bump` implementation which will handle attempts to bump it from inside.
