### ISSUE TITLE
Resizing viewport before it is initialized causes graphics to be misaligned on Linux

### ISSUE THREAD

**Issue by Chemrat** [griefly/griefly#223]
Steps to reproduce:
- Launch the game
- Before the game starts, resize the game window
- Enjoy misaligned graphics

Resizing the viewport again doesn't fix it

Illustration by @mechmind:
![Bug](http://files.mechmind.net//2016-03-28-221419_1436x849_scrot.png)

**Comment by mechmind** [comment]
Can be an edge case of system setup. Does affect nvidia users but works fine on intel graphics.

**Comment by Chemrat** [comment]
Seems to be fixed with #384
