### ISSUE TITLE
qDebug, qWarning etc redirect to file

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#229]
If flag -output_redirect is setted

**Comment by kremius** [comment]
And also remove SYSTEM_STREAM (or make it qDebug()?)

**Comment by shelltitan** [comment]
void myMessageOutput(QtMsgType type, const QMessageLogContext &context, const QString &msg)
{
    QString error_msg;
    switch (type) {
    case QtDebugMsg:
        error_msg = QString("Debug: %1").arg(msg);
        break;
    case QtWarningMsg:
        error_msg = QString("Warning: %1").arg(msg);
        break;
    case QtCriticalMsg:
        error_msg = QString("Critical: %1").arg(msg);
        break;
    case QtFatalMsg:
        error_msg = QString("Fatal: %1").arg(msg);
        abort();
	}
	QFile logs("error log");
	logs.open(QIODevice::WriteOnly | QIODevice::Append);
	QTextStream out(&logs);
	out << error_msg << endl;
}

Something like this would be okay?

**Comment by mechmind** [comment]
Log file should be opened once, at program startup and remain opened during execution and flushed at exit. Also logger should write source file and line number.

**Comment by shelltitan** [comment]
As I seen the qDebug,qWarning has uses call-back mechanism,     qInstallMessageHandler(myMessageOutput);

**Comment by kremius** [comment]
1. The file should be opened only once. That means that file (or more likely stream) should be global variable in the file.
2. You may use info from `QMessageLogContext`, and it will be useful in some cases. However, the info will be availiable only if certain defines are enabled.
3. A datetime stamp is needed in the log.
4. It is needed to handle `QtInfoMsg` messages in order to avoid some warnings:
```
#if QT_VERSION >= QT_VERSION_CHECK(5, 5, 0)
    case QtInfoMsg:
        logstream << "Info, " << datetime << ": " << msg << endl;
        break;
#endif // QT_VERSION
```
something like that.

Overall the aproach is right

**Comment by shelltitan** [comment]
```
QFile logs("error log");

void myMessageOutput(QtMsgType type, const QMessageLogContext &context, const QString &msg)
{
    QTextStream logstream(&logs);
    QString datetime = QDateTime::currentDateTime().toString();
    switch (type) {
    case QtDebugMsg:
        logstream << "Debug, " << datetime << ": " << msg << " " << context.file << " " << context.line << " " << context.function << endl;
        break;
    case QtWarningMsg:
        logstream << "Warning, " << datetime << ": " << msg << " " << context.file << " " << context.line << " " << context.function << endl;
        break;
    case QtCriticalMsg:
        logstream << "Critical, " << datetime << ": " << msg << " " << context.file << " " << context.line << " " << context.function << endl;
        break;
    case QtFatalMsg:
        logstream << "Fatal, " << datetime << ": " << msg << " " << context.file << " " << context.line << " " << context.function << endl;
        abort();
#if QT_VERSION >= QT_VERSION_CHECK(5, 5, 0)
    case QtInfoMsg:
        logstream << "Info, "  << datetime << ": " << msg << " " << context.file << " " << context.line << " " << context.function << endl;
        break;
#endif // QT_VERSION
	}
}
```
and

```
if(GetParamsHolder().GetParamBool("-output_redirect"))
    {
        logs.open(QIODevice::WriteOnly | QIODevice::Append);
        qInstallMessageHandler(myMessageOutput);
    }
```

**Comment by shelltitan** [comment]
DEFINES += QT_MESSAGELOGCONTEXT should be in qmake?

**Comment by kremius** [comment]
Here is not the place for the implementation details in code. Overall approach is right, but there is a lot of small specifics, so if you would like to make this issue then open the pull request.

Our build system is not qmake, so it should not be in qmake. We use CMake.

**Comment by mechmind** [comment]
Also please name it "error.log".
