### ISSUE TITLE
Enlarge map size

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#230]
It should be 250x250 at least

**Comment by mechmind** [comment]
Coupled with #197

**Comment by shelltitan** [comment]
I could ask a ss13 mapper to map a station, if that's good.

**Comment by kremius** [comment]
I doubt that it will be helpful on this stage of the development. I will do it myself.

**Comment by kremius** [comment]
`bool` settings map editor support because `anchored_` is needed

**Comment by kremius** [comment]
1. More signs
2. Mode medical analyzers in left part of the map, and more atmos tools in right part of the map
3. More various floors
4. More professions (assistant, security, doctor, barman, clown)
5. Change starting texts

**Comment by kremius** [comment]
6. Better atmos tool output

**Comment by kremius** [comment]
7. Random human body types (black, white, etc)

**Comment by kremius** [comment]
Seems like done overall
