### ISSUE TITLE
Pull items

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#233]

**Comment by shelltitan** [comment]
Adding 2 IdPtr to IOnMapBase could do the job, just the corner move like up. left, left are questions, could speed up the pulled object temporary so it would move  up left fast, and if the guy move after the up then it would set the speed of the item back and of course the projectiles wouldn't be able to be pulled so there should be a check for it and same for anchored objects.

**Comment by kremius** [comment]
This issue looks simple, but actually it is a quite tricky.
1. No new variables should be added to `IOnMapBase` - it will be just too much just for the pull feature. It is fine and needed to add one `IdPtr` to `Human` class (something like `pulled_`).
2. Overall pull logic should be in the `Human::TryMove` function. It is needed to check if pulled object is still near. If pulled object is valid then **after** successfull `IMovable::TryMove` it will be needed to call `TryMove` on the pulled object - some direction calculation will be required.
3. In the human process it will be needed to check if `pulled_object_` is still valid each tick. (because pulled object can be moved)
4. And it will be needed to add new button on the interface (stop pull), and the way to pull something (it will be needed to add handling ctrl + click in the representation).

**Comment by shelltitan** [comment]
I was checking QT forums and I didn't found any function like in sfml that can check if the key is held down at the moment so the click+not modifiers aren't that easy and I don't want to touch the representation because I'm not that familiar with qt.

**Comment by kremius** [comment]
I will add some additial click messages (and also some convenient way to add new).

**Comment by kremius** [comment]
#298
