### ISSUE TITLE
Rotation of objects

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#234]
Players should be able to rotate something

**Comment by shelltitan** [comment]
Something like this would be fine?
```
RotationAction(IdPtr item)
{
    if(!item->anchored)
        {
        if(!IdPtr<Projectile> projectile = item)
              {
              Rotate(item->GetDir + 1 % 4)
              }
        }
}
```

**Comment by kremius** [comment]
Yeah, something like that will be fine, but it will be needed to add new click rotation message (similar with pull items). I think, p + leftclick is suitable for this task.

**Comment by shelltitan** [comment]
Okay can I do pull request on gettile and this together?

**Comment by kremius** [comment]
I think it will be fine.

**Comment by kremius** [comment]
#298
