### ISSUE TITLE
Some initial medicine and medics

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#236]

**Comment by shelltitan** [comment]
Adding basic band aid should be enough I think?(most of damage would be physical in the game anyway.)

**Comment by kremius** [comment]
This issue more about some new medical mechanics. Now there is only physical damage, so it is needed to add some new one. For example whould be nice to have some oxygen damage (it  diminishes over time). Maybe something else, it is needed to think about that. Some healing items sure are needed.
So the issue is confusing overall -> maybe it will be better to do it later when core issues from current milestone will be finished.

**Comment by shelltitan** [comment]
Addig 3 types of damage and one medicine for each? Also the regens can be exponentionally slowing as the damage decrease or just constant regeneration is finn?

**Comment by shelltitan** [comment]
Fine*

**Comment by shelltitan** [comment]
Fine*

**Comment by kremius** [comment]
I think there should be 3 types of damage (as you said): physical damage, cold/fire damage (if temperature too high or too low) and suffocation. Regeneration should be only for suffocation damage, so it is not needed to medicine for it.
Also, medical scanner will be useful I think.

**Comment by shelltitan** [comment]
Okay.Physical is brute in SS13 I think, burn damage should be like I get the temperature from tile and get the difference between the average temperature (297 kelvin) and weight the base burn damage per tick with it?

**Comment by kremius** [comment]
Yeah, it is brute.
Something like that will be fine.

**Comment by kremius** [comment]
+ also medics uniform is needed

**Comment by shelltitan** [comment]
Should I add white tiles and the medbay logo, so you can map a madbay.

**Comment by kremius** [comment]
Logo may be a little bit overkill for now, but tiles will be helpful.

**Comment by shelltitan** [comment]
I meant the one that's on the wall.

**Comment by kremius** [comment]
I probably do not remember that. If it is like 1 tile item then sure, you can do that.

**Comment by shelltitan** [comment]
http://i.imgur.com/RjdRcSc.png You can see them on the wall they are one tile.

**Comment by kremius** [comment]
Yeah, it will be helpful too I think.

**Comment by shelltitan** [comment]
Lasers do burn damage instead of brute?

**Comment by shelltitan** [comment]
Maybe the pressure can make brute damage too?

**Comment by kremius** [comment]
Lasers may do burn damage.
The pressure may do brute damage in future, but now this feature may make space too deadly.

**Comment by shelltitan** [comment]
The oxygen and burn icon can be added too.

**Comment by shelltitan** [comment]
I can make max_health and calculate the actual health by using the damages.

**Comment by kremius** [comment]
Probably not the burn icon, but a temperature indicator.

**Comment by shelltitan** [comment]
Yeah sorry I mean that one.

**Comment by shelltitan** [comment]
The temperature implementation would use the temperature of the body normally so actually later the current implementation will change a bit but not much.

**Comment by shelltitan** [comment]
The temparature is around 40(K? or Celsius?).

**Comment by kremius** [comment]
All macroscopic parameters of the atmos do not have defined units of measurement. They are just some abstract numbers. Constants for various interactions (e.g. human burn damage) should be picked manually.

**Comment by shelltitan** [comment]
Okay I rescale then I bit (40 seems to be the indoor base so I rescale according to that).

**Comment by shelltitan** [comment]
Can I rescale the maximum health(to 10000) so we can represent health like it is in ss13(2 digit precise).

**Comment by kremius** [comment]
Sure, you can do this.

**Comment by kremius** [comment]
Done by #361, will test & close

**Comment by kremius** [comment]
FIXME: health hud indicator shows critical state from 0% to 10%

**Comment by kremius** [comment]
Tested
