### ISSUE TITLE
Simple bar

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#237]
Only beer, vodka and tea.

**Comment by shelltitan** [comment]
Should they have any effect?

**Comment by kremius** [comment]
Nope.
Maybe only some simple ones (without holding any state in a `Human` object) - like small chance to fall with some text when someone takes a sip from a bottle with vodka.

**Comment by shelltitan** [comment]
Maybe this should be merged with health system so they could have medicine like effects, like painkiller effect or something like this.

**Comment by kremius** [comment]
In future - definitely.
The purpose of the issue is to provide a little bit more place for player interactions, nothing more. A good implementation of the bar is heavily blocked by chemistry system.

**Comment by shelltitan** [comment]
Should I add a liquid classroom and containers or just add them as items?

**Comment by shelltitan** [comment]
I meant class.

**Comment by kremius** [comment]
No, just items. All beverages can be done as one class with `bool full_;` variable and the `QString` type variable.

**Comment by shelltitan** [comment]
"Glup" sound for drinking and should it post something in chat?

**Comment by kremius** [comment]
Something like `Morgan James takes a gulp of water` I think.
If there is a good sound for gulp them it is reasonable to use it (just it will be really annoying to hear bad "gulp")

**Comment by shelltitan** [comment]
I'm not sure if there is icon for a tea bottle so I will use maybe a glass or similar icon as place holder.

**Comment by shelltitan** [comment]
"Types mismatch: expected - 2, actual - 55"
Aborted (core dumped)

I cannot open the brig_small.gen neither atmos_test.gen.

**Comment by kremius** [comment]
Unfortunately, the map and mapgen format was changed. So it is needed to create new map, old maps won't work. `test.gen` can be used for tests.

**Comment by kremius** [comment]
Closed by #356
