### ISSUE TITLE
Some issues with adding new cpp file

### ISSUE THREAD

**Issue by shelltitan** [griefly/griefly#258]
How to add new .cpp file to compile?

**Comment by kremius** [comment]
You should create new *.cpp file manually and after that rerun CMake. CMake should grab all files with *.cpp extension automatically.

**Comment by shelltitan** [comment]
Well I did this but when I start make I get linker errors.

**Comment by kremius** [comment]
Could you please provide more info about the issue (your os and compiler output with erors)?

**Comment by mechmind** [comment]
Also you can commit your changes into separate branch and link it here.

**Comment by shelltitan** [comment]
Linking CXX executable KVEngine
CMakeFiles/KVEngine.dir/Sources/core/objects/Tile.cpp.o: In function `CubeTile::TargetTileLoc(id_ptr_on<IOnMapBase>, id_ptr_on<Projectile>) const':
/home/pisti/Desktop/ss13/griefly/Sources/core/objects/Tile.cpp:445: undefined reference to `Projectile::MakeMovementPattern(sf::Vector2<int>)'
CMakeFiles/KVEngine.dir/Sources/core/objects/Human.cpp.o: In function `Human::processGUImsg(Message2 const&)':
/home/pisti/Desktop/ss13/griefly/Sources/core/objects/Human.cpp:175: undefined reference to `Revolver::Shoot(id_ptr_on<IOnMapObject>)'
CMakeFiles/KVEngine.dir/AutogenMetadata.cpp.o: In function `Projectile::_Z_creator(unsigned long)':
/home/pisti/Desktop/ss13/griefly/Sources/core/objects/Projectiles.h:11: undefined reference to `Projectile::Projectile(unsigned long)'
CMakeFiles/KVEngine.dir/AutogenMetadata.cpp.o: In function `Projectile::Projectile(NotLoadItem)':
/home/pisti/Desktop/ss13/griefly/Sources/core/objects/Projectiles.h:11: undefined reference to `vtable for Projectile'
CMakeFiles/KVEngine.dir/AutogenMetadata.cpp.o: In function `Revolver::_Z_creator(unsigned long)':
/home/pisti/Desktop/ss13/griefly/Sources/core/objects/Revolver.h:8: undefined reference to `Revolver::Revolver(unsigned long)'
CMakeFiles/KVEngine.dir/AutogenMetadata.cpp.o: In function `AmmunitionBox::_Z_creator(unsigned long)':
/home/pisti/Desktop/ss13/griefly/Sources/core/objects/Bullets.h:8: undefined reference to `AmmunitionBox::AmmunitionBox(unsigned long)'

**Comment by mechmind** [comment]
@shelltitan can you commit all your changes into separate branch, push it to your fork and post there link to this branch?

**Comment by shelltitan** [comment]
https://github.com/shelltitan/griefly

**Comment by mechmind** [comment]
How do you run build? Just checked out your branch and ran `make` and got some syntax errors. Try to build project with just `make`.

**Comment by kremius** [comment]
In future try to use `git add .`, `git commit -m "message"` and `git push` (any git manual should provide more info about that stuff). It is much better than github files upload.
Overall, you should call `make` from the root of the project (not from the `bin` folder), i.e. it is needed to run `make` in the same folder with file `README.md`. `Makefile` in the root should internally handle everything right.

**Comment by shelltitan** [comment]
I did that but the one that I didn't forked does something different from that I forked.

**Comment by mechmind** [comment]
Do you cloned repo from griefly/griefly first and then forked to your github account? In that case your local repo will point to original repo and push will fail. You need to set correct repository upstream to push to your fork: `git remote set-url origin git@github.com:shelltitan/griefly.git` and push with command `git push origin master`.

**Comment by kremius** [comment]
Seems like you are doing something wrong or have broken something in your version. I would recommend to get a clean version and try to apply some small changes (e.g, add one cpp file and check if it will compile).

**Comment by mechmind** [comment]
@shelltitan did you fix the build?

**Comment by shelltitan** [comment]
Yeah the one I forked is working as it should the other that I just cloned from the main wasn't because it was broken like kremius said.

**Comment by shelltitan** [comment]
Thanks for the help both of you, this git thing was new to me so it helped a lot.

**Comment by kremius** [comment]
@shelltitan 
**\*.dmi** file is basically **\*.png** with some metadata info in the `zTXt` chunk.
So you can open a dmi file in some usual image viewer/editor and look into its metadata with a metadata viewer. On Windows I use TweakPNG for a metadata check, I have heard that ImageMagick ([http://www.imagemagick.org/](url))  can help in this task on linux, but I have never tried it.

**Comment by shelltitan** [comment]
@mechmind I did finish what I was working on the result is attached, though there are problems(some which I was expecting and some which wasn't expected...)
![optimised](https://cloud.githubusercontent.com/assets/19911258/16237871/847d1ea0-37de-11e6-95ec-a2ba7dd0e19b.gif)

**Comment by mechmind** [comment]
Glad to see you are making progress towards implementing a new feature for Griefly! After fixing bugs you'll need to clean git history and make a pull request so we can review changes and prepare patch for merge into main codebase. I've tried to fix your history locally but seems like it will be easier to copy current state of your master somewhere, then reset to original state:
`git reset 92eeaf93b9ba59926db574347f1525cc96f63513`
 (this is a last commit from @kremius  in your fork). After that you need to just commit changes again: 
`git add .; git commit -m '#235 implement guns'`
 and force-push branch to github:
`git push origin +master`
Then you will be able to create pull-request through github web interface. Good luck!

**Comment by shelltitan** [comment]
I ran across a bug that I don't know why does it happen, it is related to the networking.When you open 2 client and there isn't a collision with walls(it isn't defined so if it collides then it will crash I knew about this) the clients get segmentation faults and dumped, but if I use it with one client as you can see in the gif then this isn't happening.

**Comment by mechmind** [comment]
OK, make pull request and we will try to hunt it down.

**Comment by shelltitan** [comment]
Pull?Not push?

**Comment by mechmind** [comment]
First you push changes to your own fork then use the button "make pull request" in web interface.

**Comment by shelltitan** [comment]
It doesn't let me push the changes after I did the reset and the other thing.

**Comment by mechmind** [comment]
Even `git push origin +master` fails?

**Comment by shelltitan** [comment]
Nope I could do git push origin +master it's done.

**Comment by shelltitan** [comment]
@mechmind is it possible that you rename a file and it's `.cpp` doesn't get compiled and you get linking errors?

**Comment by kremius** [comment]
@shelltitan Every time when you change anything in the project structure (new file, renaming, deletion) it is needed to run CMake again.

**Comment by shelltitan** [comment]
Not make but cmake?

**Comment by kremius** [comment]
@shelltitan Ah, totally forgot that on Linux it is call CMake via Make. My bad, than just `make` should be enough.

**Comment by shelltitan** [comment]
@kremius I did it but I get linking error, and it because the LeserGun.cpp doesn't get compiled(and at linking the constructor is missing.)

Error code
`CMakeFiles/KVEngine.dir/AutogenMetadata.cpp.o: In function `LaserGun::_Z_creator(unsigned long)':
/home/pisti/Desktop/ss1/griefly/Sources/core/objects/LaserGun.h:8: undefined reference to `LaserGun::LaserGun(unsigned long)'
CMakeFiles/KVEngine.dir/AutogenMetadata.cpp.o: In function `LaserGun::LaserGun(NotLoadItem)':
/home/pisti/Desktop/ss1/griefly/Sources/core/objects/LaserGun.h:8: undefined reference to `vtable for LaserGun'
`

**Comment by shelltitan** [comment]
By the way before I did this everything was working with projectiles in this one I just added some sound and 1 more weapon.(I should make a Weapon.cpp and Weapon.h and put revolver and laser gun here.)

**Comment by kremius** [comment]
@shelltitan Check your `Makefile` for changes. `git diff Makefile` should show nothing.

**Comment by shelltitan** [comment]
@kremius It doesn't show anything

**Comment by kremius** [comment]
@shelltitan  where did you place `LaserGun.cpp` file?

**Comment by shelltitan** [comment]
@kremius griefly/Sources/core/objects/

**Comment by kremius** [comment]
Well, everything seems ok for me. Maybe @mechmind will be able to figure it out.

**Comment by shelltitan** [comment]
@kremius well I move the code to a `weapon.cpp/.h` then try it

**Comment by shelltitan** [comment]
Well I pushed my changes then removed my old source and clone a new one, and it's working now.

**Comment by kremius** [comment]
@shelltitan It is good that you have found workaround for the issue, but overall there is something fishy here. Probably there is some trouble with build on linux. I will try look into this more carefully.

**Comment by shelltitan** [comment]
When I did ask the first question I did similar things renaming might cause a bug.

**Comment by kremius** [comment]
Reproduced and configrmed: currently `make` command does not work correctly.
