### ISSUE TITLE
Mouse click message to action over object

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#269]
1004 - mouse click -> action over object
`{"obj":42}` -> 
`{"action":"rclick","obj":42}`
`{"action":"rotate","obj":83}`
etc
Verbs-friendly approach

**Comment by shelltitan** [comment]
But pull will be key-binded then?

**Comment by kremius** [comment]
Because #234 needs some button + click event.

**Comment by shelltitan** [comment]
Wouldn't be that a better if there would be a box that only visible to the original right clicker so he can select pull/rotation on an object so rclick wouldn't be sent to the server but the action which was selected from the box would be only sent.

**Comment by kremius** [comment]
There aren't any right click box right now and it will not appear soon, so for now it will be combinations of click + some button for such actions.

**Comment by mechmind** [comment]
Server implementation lives in https://github.com/griefly/griefly/tree/269-extend-mouseclick-message
