### ISSUE TITLE
Recursive GetTile

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#270]
Call `GetTile` on owner until owner is zero, then return object.

**Comment by shelltitan** [comment]
```
IdPtr<CubeTile> GetTile(IdPtr item)
{
    if(!item->GetOwner())
    {
          return item;
    }
    else
    {
          return GetTile(item->GetOwner());
    }
}
```

**Comment by kremius** [comment]
Well, something like that, but it should be `IOnMapBase` member (like `GetOwner`). And I think it will be better to name it `GetRoot` (because the top of the owner hierarchy is not always tile).

**Comment by kremius** [comment]
#298
