### ISSUE TITLE
Windows CI

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#285]
http://www.appveyor.com/ looks like it is free for open source projects

**Comment by MartiUK** [comment]
I've used it before, working on getting griefly building now.

**Comment by MartiUK** [comment]
Here's my current progress, having issues with getting zlib and libpng recognised at the moment.

https://ci.appveyor.com/project/MartiUK/griefly

**Comment by shelltitan** [comment]
I think this is related to yours:  https://stackoverflow.com/questions/36992243/appveyor-c-cmake-png-package-compilation-error

**Comment by MartiUK** [comment]
Yeah, got it. I didn't think to build libpng first before building the whole project. I need coffee...

**Comment by kremius** [comment]
That's actually pretty inconvenient thing - libpng does not have official binaries for windows (as far as I know). I have bulit them manually, but I am not sure if it will be easy to do that on AppVeyor - it will be needed to patch `zlib.props` file with path of `zlib`. 
Maybe it will be easier to get compiled library from NuGet or Chocolatey.

**Comment by MartiUK** [comment]
You can definitely run nuget through cmake, that'll be easier to do than manually downloading SFML and libpng beforehand.

**Comment by kremius** [comment]
It probably will be better just download and build zlib & libpng from sources during cmake generation (like gtest lib now).

**Comment by kremius** [comment]
Just to avoid misunderstandings: this issue should not be blocked by #302, because #302 will not be done soon (at least, by me).
