### ISSUE TITLE
CMake policies warnings

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#287]
`Policy CMP0043 is not set:`

**Comment by kremius** [comment]
`cmake_policy(VERSION major.minor[.patch])`

**Comment by MartiUK** [comment]
Do we enforce a higher cmake version? I'm currently using 3.6.1, appveyor uses 3.5.2 and travis uses >= 3.0

**Comment by kremius** [comment]
Will test fix

**Comment by kremius** [comment]
Tested, fixed
