### ISSUE TITLE
Welding the doors

### ISSUE THREAD

**Issue by shelltitan** [griefly/griefly#307]
I accidentally found that after I weld the door I cannot undo it.

**Comment by shelltitan** [comment]
I think it's related to the overlay.

**Comment by kremius** [comment]
In the `Door.cpp` file there is line 120
```
    if (IdPtr<Weldingtool> w = item)
    {
        if (IsClosed() && w->Working())
        {
            Weld();
        }
        return;
    }
```
`IsClosed` returns `false` if door state is `WELDED`, so it is needed also check if the door state is `WELDED` here.

**Comment by shelltitan** [comment]
if ((IsClosed() && w->Working()) || IsWelded())
        {
            Weld();
        }

**Comment by kremius** [comment]
In that case it will be possible to unweld door when welding tool is not working, so it is more like
```
if ((IsClosed() || IsWelded()) && w->Working())
{
    Weld();
}
```

There is no any `IsWelded` function (but it may be implemented).

**Comment by shelltitan** [comment]
Well maybe a function that returns the state will be better, because almost every state has a function.
