### ISSUE TITLE
Windows build failing if tests are disabled

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#308]
It is needed to link `Qt5::WinMain` if building without tests (probably).
Also the "/SUBSYSTEM:CONSOLE" flag is applied only for release builds with tests.

**Comment by MartiUK** [comment]
I've fixed this in the appveyor pull request

**Comment by kremius** [comment]
I am not sure about that.
As far as I can see #303 just always set `/SUBSYSTEM:CONSOLE` flag in release build.
It has two weak points:
1. The app will have a console window. It is fine during development and needed for tests execution, but redundant for the true release version - there should be only 1 window (game window).
2. It probably won't work in Debug build (because only `LINK_FLAGS_RELEASE` flag is setted).
