### ISSUE TITLE
Rework dmi metadata parsing

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#327]
Now it is too messy

**Comment by kremius** [comment]
Tests now do not cover multiple failure cases, and they won't until rework because a lot of copypaste.

**Comment by kremius** [comment]
Better make separate extractor.
`human.dmi` -> `human.png` + `human.png.metadata.json`

**Comment by Redict** [comment]
Working on it.

**Comment by kremius** [comment]
Imagemagick + python script

**Comment by Redict** [comment]
Not good solution, Im working onto DMI that implemented in BYOND by disassembling

**Comment by mechmind** [comment]
Command to extract metadata from dmi:
`$ identify -format "%[Description]" file.dmi`

**Comment by kremius** [comment]
@Redict Yes, disassembling is not good solution, I have to agree.

**Comment by Redict** [comment]
@kremius You will able to do like that DMI->Frames->Frame->FramePixels and get any of them

**Comment by kremius** [comment]
@Redict I don't understand you. DMI is just simple png with some metadata in `zTXT` png chunk. Metadata format is already well examined - https://github.com/griefly/griefly/blob/master/sources/representation/Metadata.cpp
There is no any room for disassembling.

**Comment by Redict** [comment]
@kremius I am disassembling a better OOP solution for it

**Comment by kremius** [comment]
@Redict You can do whatever you want, but you should not expect that your code will be used in Griefly.

**Comment by kremius** [comment]
Done
