### ISSUE TITLE
Game crash on empty hand attack any non-pickable object

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#329]

**Comment by shelltitan** [comment]
There is a code that doesn't make sense I removed it and it works for me.
```
    {
        // Disable movement
        VDir force = item->force_;
        VDir revert_force(-1 * force.x, -1 * force.y, -1 * force.z);
        item->ApplyForce(revert_force);
    }
```

**Comment by kremius** [comment]
This code causes crash, but it makes sense.

**Comment by shelltitan** [comment]
@kremius I thought that forces are only for pushing items (I mean in-game of course).

**Comment by kremius** [comment]
@shelltitan Forces are for everything. For example, when atmos moves some object it uses forces systems. Some things now does not use forces due some limitations of the current force system, but when #279 and #272 will be done forces will be used everythere.

**Comment by shelltitan** [comment]
@kremius Well atmos do pushing so I included atmos when I said that, but what does everything mean, do you plan to add realistic force and velocity and displacement calculations?

**Comment by kremius** [comment]
@shelltitan When a human makes movement (a player presses a some arrow button) then it uses the forces system too. 
Realistic is too ambiguous concept (cause it is a tile-based game), but some kind of momentum, energy, and etc probably will be added.
