### ISSUE TITLE
Windows and grille smashing

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#330]
Bullets and items

**Comment by shelltitan** [comment]
Should I add hp to structure or only to windows and grille? I can make only them destructible either way.

**Comment by kremius** [comment]
It is reasonable to make `Breakable` helper class (`class Breakable : public Structure`).
`FlatGlass` and `Grille` should be inherited from `Breakable`.
The `Breakable` class will have a hitpoints field, a `AttackBy` redefinition and etc.

**Comment by shelltitan** [comment]
Are grilles transparent?

**Comment by kremius** [comment]
Yes, they are. A grille is a part of a standard window tile in the SS13.

**Comment by shelltitan** [comment]
Where should the shard drop when the window is destroyed?

**Comment by kremius** [comment]
On the same tile with the window.

**Comment by shelltitan** [comment]
Bullets go through one grille but will hit the 2nd this is because the spawn should I add this as a separate issue or just do it with this?

**Comment by kremius** [comment]
Better to create separate issue.

**Comment by kremius** [comment]
by #334
