### ISSUE TITLE
Projectiles creation bug

### ISSUE THREAD

**Issue by shelltitan** [griefly/griefly#335]
When a projectile is created it should check if the spawning tile is passable or not.

**Comment by shelltitan** [comment]
Well I think this bug is same as the human one was. If you push a closet, the bullet can go through it while it doesn't get stopped.

**Comment by kremius** [comment]
A projectile creation differs from a projectile movement, so it is not the same.
Now you can stand just near a window and start shooting -> the far glass will be broken.
Now you even can shoot through transparent doors and tiles, and that's not good.

**Comment by kremius** [comment]
Fixed by #341
