### ISSUE TITLE
Silent crash if metadata.json cannot be found

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#347]
Сheck it and crash intentionally if missing

**Comment by dangranos** [comment]
What is that `metadata.json` thing actually?

**Comment by kremius** [comment]
`metadata.json` is a file generated by `metadata_generator.py` script. It contains info about all game classes (i.e. classes that has `IMainObject` class at the top of the inheritance hierarchy & have some macroses in declarations in headers). There are a class name, a type name, a base class and a list of the declared variables for each class in the file.  
C++ does not have built-in reflection feature (aside `dynamic_cast` & `typeid`, but they aren't handy), so `metadata.json` is a part of the own reflection implementation. 
It used in two (kind of three) places:
1. `autogen.py` uses the file during `AutogenMetadata.cpp` file generation (build stage).
2. On the game start `metadata.json` is loaded and the table of casts between game classes is generated - a fast `dynamic_cast` replacement. 
3. (Kind of) The map editor is using data from `AutogenMetadata.cpp` for variables & classes. In future the map editor probably will load data about classes, variables and etc directly from `metadata.json`, but it requests certain changes.
