### ISSUE TITLE
Proper CPU load

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#348]
CPU load should be based on `QElapsedTimer`. Current implementation works bad on Linux (shows 20% minimum) because `QWaitCondition` sleeps a little bit more than expected (and it is proper behavior).

**Comment by shelltitan** [comment]
For me this is between 8-12% and I use Linux.

**Comment by shelltitan** [comment]
My cpu load is -4.3 after this commit.

**Comment by kremius** [comment]
`¯\_ツ_/¯`
It has not worked properly anyway. What is your machine specs?

**Comment by shelltitan** [comment]
Intel® Core™ i5-4570 CPU @ 3.20GHz × 4, 8Gb RAM, GeForce GTX 660
