### ISSUE TITLE
"Master client is not connected"

### ISSUE THREAD

**Issue by aash29** [griefly/griefly#362]
Hi! I compiled successfully, but cannot login, getting "Master client is not connected" error
with both launcher and command line KVEngine
I modified auth.json by making example-user admin

**Comment by shelltitan** [comment]
Do you login on it?

**Comment by kremius** [comment]
1. Do you connect to your own server?
2. Have you provided login & password via command line or in the launcher?

**Comment by aash29** [comment]
I connect to my own server, tried providing login info both with launcher and with command line. Result is identical,

> Connection failed!
> Socket error: 1, reason: Master client is not connected
> 
> If you would like to reconnect then do it manually (close the game window and start the game again)
>

**Comment by shelltitan** [comment]
Works fine to me. What is the command you used?

**Comment by kremius** [comment]
What is your system?
Can you provide yours `auth.json` file too?
Also, output from the server will be helpful too.

**Comment by aash29** [comment]
The command I use is 
`./KVEngine mapgen_name=maps/brig_small.gen -auto_connect login=example-user password=1234
`

```
tryConnect()
socketConnected()
"{\n    \"game_version\": \"v0.3.1-526-g6f6a\",\n    \"guest\": false,\n    \"login\": \"example-user\",\n    \"password\": \"1234\"\n}\n"
Master client is not connected
socketError()
QAbstractSocket::RemoteHostClosedError
```

auth.json:
```
{
    "admin": {
        "passhash": "6b3a55e0261b0304143f805a24924d0c1c44524821305f31d9277843b8a10f4e",
        "is-admin": true
    },
    "example-user": {
        "passhash": "1234",
        "is-admin": true
    }
}
```

**Comment by shelltitan** [comment]
Is it a fresh pull?  If it is type `./KVEngine mapgen_name=maps/test.gen -auto_connect login=example-user password=1234`

**Comment by aash29** [comment]
It is a fresh pull, but changing map doesn't help.

**Comment by kremius** [comment]
Works for me with your `auth.json` and string.
Have you restarted server after `auth.json` fix? The server will not update database until restart.

**Comment by aash29** [comment]
Yes, that was it  - thanks!
