### ISSUE TITLE
Migrate to Visual Studio 2015 as main Windows compiler

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#368]
Now 2012 is used as main compiler and therefore many C++11 features are not eligible (e.g. `constexpr`).
Seems like 2015 studio finally has decent C++11 support.

**Comment by Redict** [comment]
You've better port it on VS17

**Comment by kremius** [comment]
Yes, it may be reasonable to use 2017 compiler. Seems like AppVeyor supports it, so everything should be fine.

**Comment by kremius** [comment]
Kind of blocked by #285

**Comment by kremius** [comment]
Unfortunately, Qt packages are missing for msvc17 images, so 2015 for a while.
