### ISSUE TITLE
Render artifacts on linux

### ISSUE THREAD

**Issue by mechmind** [griefly/griefly#382]
As of 1d84a5f52 master game screen start to stutter after some time or window switch.

**Comment by kremius** [comment]
Probably some double buffering bug, because seems like it is handled poorly now (`GetGLWidget()->swapBuffers();` can be called twice).

**Comment by Lourens-Rich** [comment]
@kremius, I wrote you email about this, earlier.

**Comment by kremius** [comment]
@Lourens-Rich It is better to link exact commit then you talk about a specific build version, because it is unclear that do you mean by "this". 30% CPU does not sounds bad, so probably you imply that before the load was less. In that case it will be helpful to provide the previous CPU load too.

**Comment by kremius** [comment]
Temporally in 0.4 - I have an idea how to fix it quickly. If the idea will not work out then the issue will be postponed.

**Comment by mechmind** [comment]
@Lourens-Rich if you have similar problems, please report version of qt, drivers and xorg you have installed.

**Comment by Lourens-Rich** [comment]
I use Arch Linux. Xorg: 1.19.1 Qt: 5.8 (I saw this problem on 5.7 too.)

**Comment by kremius** [comment]
@mechmind @Lourens-Rich 
Can you test changes? There might be a possibility that the issue was fixed.

**Comment by Lourens-Rich** [comment]
Now after changing window focus, game looks and plays very smooth. But sometimes pipes under floors was flick.

**Comment by kremius** [comment]
Seems like everything is fixed on @mechmind machine.
Anyway there will be more changes in OpenGL in the future.
