### ISSUE TITLE
Using widget size in QtOpenGL::initializeGL() results in incorrect projection matrix and black screen

### ISSUE THREAD

**Issue by Chemrat** [griefly/griefly#384]
Qt 5.7.1

glOrtho is called with widget size, which may be set to (0, 0) when initializeGL() is called
This results in a projection matrix being set in an unexpected way and breaks further rendering

Projection matrix is actually never updated, even if the widget is resized, so maybe glOrtho calls should use fixed values instead

**Comment by kremius** [comment]
@Chemrat Can you test https://github.com/griefly/griefly/commit/4c479e8bc18bbc6d44926d5d5f25034c5abc35c3 commit? `glOrtho` should be called properly now.
Also seems very similar to #223. Can you test it too?

**Comment by Chemrat** [comment]
Still not fixed, there are multiple resize events sent to QtOpenGL (window creation?, show() call, window resize) before it's resized from Representation constructor

You probably should either not rely on widget size at all or handle projection matrix in resizeGL()

**Comment by Chemrat** [comment]
Seems to be fixed now
