### ISSUE TITLE
v0.4.0 beta test

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#386]
1. Prepare windows build
2. Conduct semi-closed test (if something is horribly wrong then there will be 0.4.1 milestone)
3. Prepare changelog text
4. Prepare advertisement for the open alpha test
5. Choose the date of test
6. Spread the word in advance
7. Conduct the test

**Comment by Lourens-Rich** [comment]
I can help to share a little resource of my instance for creating a new game server.

**Comment by Lourens-Rich** [comment]
Could you ask community from Animus station to help with testing?

**Comment by kremius** [comment]
@Lourens-Rich 
The server already exists, and a new game server is not needed, but thanks for offer.
I will definitely ask Animus community for help when the time will come. The paragraph 6 ("spread the word in advance") implies asking for help in various SS13 communities.

**Comment by kremius** [comment]
The advertisement


Griefly v0.4.0 open betatest

Hi guys

Griefly is a yet another Space Station 13 remake ([link](https://grief.ly/)).
It has reached a certain point in development (v0.4.0 has been reeleased), so it is needed to somehow test if core parts of the engine work correctly.
There already were various tests, but some bugs or features can be discovered only on a large scale, so I have thought that it would be nice to involve more people in the betatest.

So if someone has some free time this sunday (the 12th of February, 2017, 18:00 UTC) then it is possible to take part in the betatest. It will be needed to download the game [here](https://grief.ly/release/win/v0.4.0) and then run `Launcher.exe` and press `Connect` button. Release notes can be found [here](https://grief.ly/release-notes-0-4-0.html).
Note that it is still a very early development, so 1) there might be horrible bugs (crashes or something else) 2) the gameplay is very shallow. If you are to encounter any bugs then it would be really helpful if you would create a [bug report](https://github.com/griefly/griefly/issues).

**Comment by kremius** [comment]
The test will be conducted the 12th of February, 2017, 18:00 UTC (this Sunday).
The advertisement will be posted by me in advance in Saturday/Sunday.

**Comment by shelltitan** [comment]
@kremius alsmost has a plus "s".

**Comment by shelltitan** [comment]
@kremius this release is missing the break commit (atleast the repo says that it's behind by 1 commit).

**Comment by kremius** [comment]
When release is made then nothing can change it, so all commits after release go to the next release.

**Comment by shelltitan** [comment]
Does the server allow the windows clients from 1 commit behind to connect? Like wouldn't the version number be different?

**Comment by kremius** [comment]
There are two main versions: the server version (it gets version during the compilation) and the master client version (it gets version during compilation also). The master client version should be greater or equal to the server version. However, usual clients should have perfect match with the master client version.
Because now server has somewhat big uptime (months), the server version now will be something like v0.3.1-blah-blah. That means that the master client (me) with v0.4.0 version will be able to connect.
However, it is probably better to update the server to v0.4.0 version anyway.
@mechmind might do it.

**Comment by mechmind** [comment]
Server has been updated to `v0.4.0`.

**Comment by shelltitan** [comment]
@kremius I think there is a bug with version numbers I cannot get the client compile to v0.4 on linux (I tried to clone and use that but it doesn't work).

**Comment by kremius** [comment]
@shelltitan You should use strictly v0.4.0 version. In order to do that you should make `git checkout v0.4.0` and after rerun cmake.

**Comment by shelltitan** [comment]
@kremius In this case the client is indeed v0.4 but the launcher doesn't use v0.4 client instead it is v3.1-smt-smt.

**Comment by kremius** [comment]
@shelltitan Try to restart launcher (press `Exit`). Probably the old launcher is still running.

**Comment by shelltitan** [comment]
@kremius Yes you are right but this is a bit weird with that red icon at top if you just press on X you have to use the luancher to reopen it and press Exit to close it.

**Comment by kremius** [comment]
@shelltitan Yep, the launcher is kind of shitty.

**Comment by shelltitan** [comment]
@kremius There seems to be some problem, like getting naked randomly?

**Comment by kremius** [comment]
The test has been conducted.
