### ISSUE TITLE
Player should be notified if it has been moved by air

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#390]
Because otherwise it is really confusing.
However, might be not that easy.

**Comment by mechmind** [comment]
Notified with sound like "vzhuh"?

**Comment by kremius** [comment]
Maybe, but the main issue here to overall somehow notify `Human` object that it has been moved by air.

**Comment by ziepeso** [comment]
Something like a text notification would work in tandem with a sound. 

> You've been knocked down by a rush of air!
