### ISSUE TITLE
request compiled lpng1612 for windows

### ISSUE THREAD

**Issue by AleksCr** [griefly/griefly#397]
I try compiled it on my MCVS 15, but it requires older compiler:
>error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.

**Then**, i download package (except sources) from there: https://sourceforge.net/projects/gnuwin32/files/libpng/1.2.37/libpng-1.2.37-setup.exe/download?use_mirror=vorboss , set PNG_LIBRARY_DIR var to path to downloaded libs, but i got error on compilation(PNG_INCLUDE_DIR var still contain the path to 1612 version of lib  ): 

>C:\Games\griefly-master\griefly-master\lpng1612\png.h:464: error: C1083: Cannot open include file: 'pnglibconf.h': No such file or directory

So, i request full (sources and binaries) version of this library.

P.S. Sorry for my bad English

**Comment by kremius** [comment]
So you may try
 - Install Visual Studio 2010 build tools.
 - Or change platform toolset for libpng to MCVS15 version (v140?).
