### ISSUE TITLE
How to install asset server?

### ISSUE THREAD

**Issue by Lourens-Rich** [griefly/griefly#399]
Please, share your knowledge.

**Comment by kremius** [comment]
Please, elaborate what you mean by "asset server" because I am not sure what you mean.

**Comment by Lourens-Rich** [comment]
I tryed to connect from second computer to first (master client), but got a error: "Unable download map" I don't changing your game map.

**Comment by mechmind** [comment]
You need to forward port 8011 (tcp) for asset server to work.

**Comment by kremius** [comment]
Also, I am not sure but 
```
var serverURL = flag.String("server-url", "http://localhost:8011/", "url of asset server")
```
server-url should be setted properly. So it should be external ip instead of localhost.

**Comment by mechmind** [comment]
@Lourens-Rich, do you still have issues with asset server?

**Comment by mechmind** [comment]
Reopen or comment if you have any issues with asset server.
