### ISSUE TITLE
Migrate to Python 3

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#425]
Title

**Comment by psykzz** [comment]
Got a list of the files that are specifically not working in py3?

**Comment by kremius** [comment]
Well, not really.
All python scripts are placed [here](https://github.com/griefly/griefly/tree/master/utils), but I have not actually tested if they will work in py3. I suppose there should not be any major issues, but still.
So this issue overall:
1. Test scripts under py3
2. Fix if something does not work
3. Update `CMakeLists.txt` & `README.md`

**Comment by fluorescent-net** [comment]
Currently [working](https://github.com/fluorescent-net/griefly/pull/1) on this issue.
