### ISSUE TITLE
Separate ObjectProcessor from ObjectFactory

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#447]
Now `ObjectFactory` has two separate tasks
1. Creating objects.
2. Calling `Process` on them (when it is needed).

They should be divided.

**Comment by shelltitan** [comment]
They have some common functions, should anything process related moved or just the `ForeachProcess`? Should it have an interface like the factory, game, etc have?

**Comment by kremius** [comment]
1. Everything process related (`ForeachProcess()`, `AddProcessingItem(quint32 item)` and related auxiliary functions & members) should be moved to `ObjectProcessor`.
2. Yes, it would be nice to have `ObjectProcessorInterface` - because otherwise it would be impossible to test `kv::Object` class only with mocks.

Overall, it should implemented similar to [physics engine](https://github.com/griefly/griefly/blob/master/sources/core/objects/PhysicsEngine.h) - as `kv::Object` subclass which will be held in `GlobalObjectsHolder`.

**Comment by shelltitan** [comment]
@kremius There is a common part between the two so keeping a refrence/pointer to factory is need I think.
