### ISSUE TITLE
Dockerize travis build

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#462]
https://github.com/griefly/griefly/search?p=1&q=travis+fix&type=Commits&utf8=%E2%9C%93

Travis changes environment for machines quite often and sometimes it breaks the build. For fine-grained control under build process it might be better to build the project in a docker image which is specially prepared for the build.

**Comment by minexew** [comment]
This gets about halfway there. RUN doesn't preserve environment changes, which sucks and I got bored.

```
FROM ubuntu:trusty

RUN apt-get update -qq
RUN apt-get install -y git make ruby software-properties-common python-software-properties

RUN add-apt-repository -y ppa:ubuntu-toolchain-r/test
RUN add-apt-repository -y ppa:beineri/opt-qt591-trusty
RUN add-apt-repository -y ppa:george-edison55/cmake-3.x
RUN apt-get update -qq
RUN apt-get install -y cmake
RUN apt-get install -y g++-5
RUN apt-get install -y qt59base
RUN apt-get install -y qt59multimedia
RUN apt-get install -y lcov
RUN apt-get install -y mesa-common-dev
RUN apt-get install -y libglu1-mesa-dev
RUN gem install coveralls-lcov
RUN /opt/qt59/bin/qt59-env.sh

ENV CMAKE_PREFIX_PATH /opt/qt59/
ENV CC gcc-5
ENV CXX g++-5

WORKDIR /srv/griefly
ADD . /srv/griefly

RUN ./make.sh -DBUILD_TESTS=ON -DBUILD_COVER=ON -DCMAKE_BUILD_TYPE=Debug
RUN cd exec && ./KVEngine --run-tests
```

It might be better to base it on Fedora, because getting non-ancient compilers is less cumbersome there

**Comment by kremius** [comment]
Apparently `python-software-properties` somehow breaks CMake ability to find python3.

**Comment by kremius** [comment]
Done
