### ISSUE TITLE
Migrate to Visual Studio 2017 as main Windows compiler

### ISSUE THREAD

**Issue by kremius** [griefly/griefly#463]
`std::optional` is available only since 2017 for example.
The main possible issue here is AppVeyor & Qt pre-built version, but seems like 2017 keeps ABI from 2015, so that should not be a major trouble.

**Comment by minexew** [comment]
Consider https://github.com/tcbrindle/cpp17_headers as an alternative short-term solution before the ecosystem catches up

**Comment by kremius** [comment]
Done in https://github.com/griefly/griefly/commit/022eb5a57ae1f34d9d9db5f26812f0a3a100277b
